### ISSUE TITLE
Update brand, copy and generation animation

### ISSUE THREAD

**Issue by markmhx** [blockstack/connect#33]
Focused around Secret Key with Blockstack mentioned in "How it works"

**Comment by jasperjansz** [comment]
- [ ] 1.2 Intro modal: Remove the third feature (so it fits on small androids) and update the copy
- [ ] 1.7 Loading screens: Update copy and images and reduce to 3 instead of 4 screens
- [ ] 1.3 How it works: update copy
- [ ] 1.4 Enter SK: Update to reference app instead of our brand
- [ ] 1.11 Connect: Update copy
- [ ] 1.12 All set!: Update copy
- [ ] Page headers: update copy to say Secret Key instead of Data Vault

**Comment by markmhx** [comment]
These changes all look good on Banter.
