### ISSUE TITLE
Use framework agnostic UI 

### ISSUE THREAD

**Issue by friedger** [blockstack/connect#81]
Something like https://stenciljs.com/ so that the library can be used also for vue apps and the like

**Comment by markmhx** [comment]
We definitely want to ensure that Connect works with Vue apps and other frameworks, though it was my assumption we had already integrated React in a way that allowed that.

Are you encountering problems while integrating with Vue?

**Comment by markmhx** [comment]
Nevermind, I'm seeing the latest Discord conversation now that confirms this is a problem. @hstove is the problem specifically that the host app needs React installed or that Connect doesn't tolerate other frameworks or both?

**Comment by hstove** [comment]
It's not a problem with not tolerating other frameworks (although there does seem to be a bug around needing to install `@blockstack/ui`, which is not related to React).

My understanding about the request here is that it would be good to not use React, to reduce the bundle size.

The problem with using any other framework is that our UI library is written for React. So, in order to use our UI in any different framework, we'd have to re-write all the styles, which could easily get out of sync.
